development: &non_production_settings
  site_url: http://localhost:7777
  site_name: MobileMailList
  admin_email: howethomas@aol.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://mobilemaillist.heroku.com
  site_name: MobileMailList
  admin_email: howethomas@aol.com  
  
production:
  site_url: http://mobilemaillist.heroku.com
  site_name: MobileMailList
  admin_email: howethomas@aol.com
